[toolchain]
channel = "1.75.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
belief_market = "11111111111111111111111111111111"

[programs.mainnet-beta]
belief_market = "11111111111111111111111111111111"

[registry]
url = "https://github.com/coral-xyz/anchor"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
